deploy:
  provider: heroku
  api_key:
    secure: MhQ+eRf6a95szy8XWcZAq0qs0z5ylvBzkkyVqwzWLwJqrnPKqafl9VeTXx6aFK1tJi5ZJKLXU3JFivjeVWRxDr901iPVfnoq1rm9BfKsZsBnqNO+ULGZKy48PawgdCZxjwtk5PIaeuKjU+4QZaZ6pHaLiAkbyNXoEjOM7yZRLSpJ2Tx5YJ1vWgVS0X2FBOclhdwnBMV4D+q0AKKYRr0kCK8S3mRvMuqwdoz//ABlWpUysJ49jmmc6jHKdWc8gi7SULLtnbWubPG1Us/y4FTa8oaXEKlIGZb7WI7IgojqKJyS6YlaVXG/fD5x/n/jaUm1jlboLQFFvcmlXp+yemyq+l1Dulk0S59ZjWJbrQ4HbAjXHajdnUMhM4cA7PusezsoLEGdEIYuwXAKsK6h8FXguSeoTYnCU2BUYfhHRMxA/RQ/xuVrTi0bKxDIV9lRTFmq7s7GjPFiJkT1LFazkwiMHzHVz95hXmVLxsewp6jmUCqDYsoQbNt1geWtH7NhZOSa7UcdqudsEdVKtqhI28VfXvtC4QUP0syiHGiVsPtdiur2NA12lB40rQwhjZxC87FxXxBAC3M7uiseFd5wgZSEGm90teSUv0SHbtyp1oebroqbm6s9DpwT6t8kTVwSe9NQLYKN7WgGf1KdUwRaOjCFY4a72SgEmvHJ86KuGorkdMI=
  app: secret-ridge-45319
  on:
    repo: camillecondrey/tests-and-CI-for-blogging-app
